# name: Docker Pull and Deploy

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#jobs:
#  deploy:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Check out code
#      uses: actions/checkout@v3

#    - name: Log in to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKER_HUB_USERNAME }}
#        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#    - name: Pull Docker image
#      run: docker pull end000/spaceshooterbackend:latest

#    - name: Run Trivy vulnerability scanner
#      uses: aquasecurity/trivy-action@master
#      with:
#        image-ref: 'end000/spaceshooterbackend:latest'
#        format: 'table'
#        exit-code: '1'
#        ignore-unfixed: true
#        vuln-type: 'os,library'
#        severity: 'CRITICAL,HIGH'

#    - name: Deploy container
#      run: |
#        docker stop spaceshooterbackend || true
#         docker rm spaceshooterbackend || true
#        docker run -d --name spaceshooterbackend -p 8080:8080 end000/spaceshooterbackend:latest

    # Дополнительные шаги могут быть добавлены здесь
